server:
  port: 8867
  servlet:
    context-path: /shiroplus
shiroplus:
  plus:
    filter-chain-definition:
      login : /login
      auth2: /**
    login-url: /login
    success-url: /user
  nacos:
    config-type: yaml