server:
  port: 18086
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      username: nacos
      password: nacos
  servlet:
    context-path: /shiroplus

management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  application:
    name: service-gateway-provider