server:
  port: 18086
  servlet:
    context-path: /shiroplus
management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  application:
    name: service-gateway-provider
  cloud:
    nacos:
      discovery:
        server-addr: common.codingeasy.com.cn:8848
      username: nacos
      password: ning,123456