server:
  port: 8869
  servlet:
    context-path: /shiroplus

spring:
  datasource:
    druid:
      #MySQL
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://47.96.93.4:3306/shiro_plus?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
      username: root
      password: '#ssll%Jke'
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 6000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.baturu.reverse.modules.*.entity
  global-config:
    #数据库相关配置
    db-config:
      update-strategy: not_null
    banner: false
  #原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
shiroplus:
  plus:
    filter-chain-definition:
      adminClient: /client/admin/**
      auth2: /admin/**

logging:
  level:
    org:
      codingeasy:
        shiroplus:
          loader:
            admin:
              server:
                dao: debug