--初始化系统配置
INSERT INTO `shiro_plus`.`sp_system`(`version`, `heartbeat_max_time`, `key_pair`, `login_valid_time`, `client_token`, `update_by`, `last_update_tm`, `init_password`) VALUES ('1.0.0', 82800000, '{\"p\":\"8nQ8tvdGp5u675UR_hg2HkEIHJUWx0QlACthdyONqAHF1pc6nV-zTEO018QAypuNzNVu6jaG2U9fZ_UAy0Tjw4t93vOZNWGE54iTOnKf5AZzOi9McwbqMpuDfHhzs1JsWVslP9FSFHfd0JBOaMV46ke2UB7YvTRWBzTMpZfLCdc\",\"kty\":\"RSA\",\"q\":\"q43cKZehXNlPza3RXAWoFCUwUxjpZiY8_Ip8K_P9Ykmagqp0dFAv8BHoMuppef3deJZ7VXU4TT4nlXfMa4uZfdVE1N9sthUKQ6FHrLD2sqoRW098Pg31HMyOJiYu09T7fJhMJLjvOpj6gGZfMiwEAbgRXn2mhLj_ABENm4ND8Jk\",\"d\":\"DgeQwk9Qqj7ZwEBrp2V42b6lPhQ0kLA74hLWyUNlP2_BPoHqc9Bk-nPpUIP3Ubgd7BuSqnzuVKKSTc2_UxfUQc1WPeipeM740qaKS6NivtmRP7QTOw0pbfgvUGEtdfXCBMENE5d2qJodmwCQZLmJ3b88PygMn-aYOxRxISbXA_E64cnoCtHkq72GF1g6n_oBWDnvZZ44vDbctq-WMk0YW0gj9r49U7rCoBV_51xaUmqdUBmAP2o_VCCdO-0tMRE5W5Ht5_qMlGSQ6TiTpan9Dk77DtEgx_DaFLqxEcKeOiYfU7xKAx8Kc7xgWaiob80767O3WqV1r2JULzCPWq7usQ\",\"e\":\"AQAB\",\"use\":\"sig\",\"kid\":\"04e3c842-1e1c-491f-ae0b-9c559729a717\",\"qi\":\"xzIoCi3faIW0NhmuN55YTlCz-IkBT2tkJcFJx3lfNZhLI09-a--NAfux0c9DyRvLSIKGALr5yiGbxpuoGECcH9dwWLbNGJdMlSIhiGhhktbM1HM7mIZ2hKKRZKRG1Njia52wQWRhC7TBE-R1PnmF1ZfbiNTgjV0nhB81t4iINdo\",\"dp\":\"1ShgYLPRyHXfydcTdIOwwLSH_ykMV7CPnzCEhgwZ9IVqfBmFDOsgZYJ5MeE-mOJdrqJO21eJAvEHfgwm4I72d-rhhOxB3G6aPD0Uw6QW8pDBKXyAB_kiWc_jr8DuZ8-lNoIto4fSU_B2cXENnotOnRrjLFmST_X9VGSVL1jexw0\",\"alg\":\"RS512\",\"dq\":\"lM8o-qscvX2DS9ZKlJgTg-X-VRZ23rSskiNOMpIiaO-Pp2hUO9CSxJvD3uaXN8qOIdvmf-p-PAJ-M5kHKQKe0hf87OohUpBNpvxvP80BMVl0VNBN5UYWKDUH2O-mDvnga-NvqSsB2MJ6CIbEbLDhiNwxtNUpbFdMWrJwK0Vh2YE\",\"n\":\"onn_FvBYvIdZ2L3QIViKkqNDHsgpHcHeibx0LMsj6T7drS1TirEYmjXSgp0l8K8k4P1Ghz4O0X3CCpaC9LKRpgyT-8neI2VcZ0tF5ni2IzWFSE3xCDStrGIiIn5L3qtzJy3RbyxjtPDDqIScCa2DYhRyeBL9a1BNhcxZGY7SqXpNqrvQzZpSP9nrlCZB1VXR32EtqF-8QChldd44R97CeVw-PpJYqd_-n4mWxqyScWF80yOUn5mjEFohadWiODzyVqPqyK8t3pE30gaNIH7fFU8hLhaeOHUu_1VYz-4Hb_uO697ybIlO1Fq9iRzk7X3-uYJs_OPhkFL5Iw2fqddxfw\"}', 660, '1234561', NULL, '2021-07-19 19:12:43', 'admin,1234567');
--初始化角色
INSERT INTO `shiro_plus`.`sp_role`(`id`, `name`, `code`, `description`) VALUES (1, '用户管理(读)', 'admin:user:read', '只有用户管理查看权限');
INSERT INTO `shiro_plus`.`sp_role`(`id`, `name`, `code`, `description`) VALUES (2, '用户管理(读写)', 'admin:user:read,write', '用户管理的查看和编辑权限');
INSERT INTO `shiro_plus`.`sp_role`(`id`, `name`, `code`, `description`) VALUES (3, '系统配置(读)', 'admin:systemSetting:read', '只有系统设置-全局配置的查看权限');
INSERT INTO `shiro_plus`.`sp_role`(`id`, `name`, `code`, `description`) VALUES (4, '系统配置(读写)', 'admin:systemSetting:read,write', '系统设置-全局配置的产看和编辑权限');
INSERT INTO `shiro_plus`.`sp_role`(`id`, `name`, `code`, `description`) VALUES (5, '权限管理(读)', 'admin:role:read', '只有权限管理的查看权限');
INSERT INTO `shiro_plus`.`sp_role`(`id`, `name`, `code`, `description`) VALUES (6, '权限管理(读写)', 'admin:role:read,write', '权限管理的查看和编辑权限');
INSERT INTO `shiro_plus`.`sp_role`(`id`, `name`, `code`, `description`) VALUES (7, '全局元数据管理(读)', 'admin:globalMetadata:read', '只有全局元数据的查看权限');
INSERT INTO `shiro_plus`.`sp_role`(`id`, `name`, `code`, `description`) VALUES (8, '全局元数据管理(读写)', 'admin:globalMetadata:read,write', '只有全局元数据的查看和编辑的权限');
INSERT INTO `shiro_plus`.`sp_role`(`id`, `name`, `code`, `description`) VALUES (9, '权限元数据管理(读)', 'admin:permiMetadata:read', '权限元数据管理的查看权限');
INSERT INTO `shiro_plus`.`sp_role`(`id`, `name`, `code`, `description`) VALUES (10, '权限元数据管理(读写)', 'admin:permiMetadata:read,write', '权限元数据管理的查看和编辑权限');
INSERT INTO `shiro_plus`.`sp_role`(`id`, `name`, `code`, `description`) VALUES (11, '客户端实例管理(读)', 'admin:instance:read', '客户端实例管理的查看权限');
INSERT INTO `shiro_plus`.`sp_role`(`id`, `name`, `code`, `description`) VALUES (12, '客户端实例管理(读写)', 'admin:instance:read,write', '客户端实例管理的查看和编辑权限');
INSERT INTO `shiro_plus`.`sp_role`(`id`, `name`, `code`, `description`) VALUES (13, 'API管理(读)', 'admin:openApi:read', 'API管理的查看权限');
INSERT INTO `shiro_plus`.`sp_role`(`id`, `name`, `code`, `description`) VALUES (14, 'API管理(读写)', 'admin:openApi:read,write', 'API管理的查看和编辑权限');
--初始化超级管理员 密码 admin123456
INSERT INTO `shiro_plus`.`sp_user`(`id`, `username`, `password`, `nickname`, `create_tm`, `status`, `last_update_tm`, `create_by`, `update_by`) VALUES (1, 'admin', 'DBYgvkvelliqAfZ/W3dt/g==', 'admin', 1, 1, '2021-07-21 17:51:43', 1, 1);